---
- hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Install Bind packages
      dnf:
        name:
          - bind
          - bind-utils
        state: latest
    
    - name: Update Centos kernel
      dnf:
        name: "*"
        state: latest

    - name: Make sure a bind is running 
      systemd:
        state: started
        enabled: yes
        name: named